#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_ROOT"

echo "[clear] Stopping stack + removing volumes"
docker compose down -v --remove-orphans || true

echo "[clear] Removing generated root .env + sentinel"
rm -f .env .installed

echo "[clear] Removing generated runtime envs (keeping *.env.example)"
shopt -s nullglob
for f in config/*.env; do
  case "$f" in
    *.env.example) ;;
    *) rm -f "$f" ;;
  esac
done
shopt -u nullglob

echo "[clear] Removing auto-generated monitoring files only (if we created them)"
for f in \
  monitoring/prometheus/prometheus.yml \
  monitoring/grafana/provisioning/datasources/datasource.yml
do
  if [[ -f "$f" ]] && head -n 1 "$f" | grep -q "Auto-generated by scripts/install.sh"; then
    rm -f "$f"
    echo "  -> removed $f"
  fi
done

echo "[clear] Done."
