#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_ROOT"

SENTINEL=".installed"

echo "[install] 1) Combine config/*.env -> root .env"

# If user cloned repo fresh and only has *.env.example, create runtime envs first.
# (Still part of step 1: you can't combine what doesn't exist.)
if ls config/*.env >/dev/null 2>&1; then
  : # ok
else
  if ls config/*.env.example >/dev/null 2>&1; then
    for example in config/*.env.example; do
      dst="${example%.example}"
      [[ -f "$dst" ]] || cp "$example" "$dst"
    done
  else
    echo "[install] ERROR: No config/*.env or config/*.env.example found."
    exit 1
  fi
fi

# Merge all config/*.env into .env (deterministic order, last value wins)
shopt -s nullglob
files=(config/*.env)
shopt -u nullglob

IFS=$'\n' files=($(printf "%s\n" "${files[@]}" | sort))
unset IFS

declare -A kv
declare -a keys

for f in "${files[@]}"; do
  while IFS= read -r line || [[ -n "$line" ]]; do
    # trim whitespace
    line="${line#"${line%%[![:space:]]*}"}"
    line="${line%"${line##*[![:space:]]}"}"
    [[ -z "$line" ]] && continue
    [[ "$line" == \#* ]] && continue
    [[ "$line" != *"="* ]] && continue

    # support: export KEY=VALUE
    if [[ "$line" == export\ * ]]; then
      line="${line#export }"
      line="${line#"${line%%[![:space:]]*}"}"
    fi

    key="${line%%=*}"
    val="${line#*=}"
    key="${key// /}"
    [[ -z "$key" ]] && continue

    if [[ -z "${kv[$key]+x}" ]]; then
      keys+=("$key")
    fi
    kv["$key"]="$val"
  done < "$f"
done

{
  echo "# Auto-generated by scripts/install.sh"
  echo "# Source of truth: config/*.env"
  echo ""
  for k in "${keys[@]}"; do
    echo "${k}=${kv[$k]}"
  done
} > .env

echo "[install]    -> wrote .env"

echo "[install] 2) Creating needed directories"
mkdir -p \
  config \
  monitoring/prometheus \
  monitoring/grafana/provisioning/datasources

echo "[install] 3) Creating needed monitoring stuff"
# Only create if missing; never overwrite user-edited files.
if [[ ! -f monitoring/prometheus/prometheus.yml ]]; then
  cat > monitoring/prometheus/prometheus.yml <<'EOF'
# Auto-generated by scripts/install.sh
global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
EOF
  echo "[install]    -> created monitoring/prometheus/prometheus.yml"
fi

if [[ ! -f monitoring/grafana/provisioning/datasources/datasource.yml ]]; then
  cat > monitoring/grafana/provisioning/datasources/datasource.yml <<'EOF'
# Auto-generated by scripts/install.sh
apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
    editable: true
EOF
  echo "[install]    -> created monitoring/grafana/provisioning/datasources/datasource.yml"
fi

echo "[install] 4) Pulling models"
if [[ ${#@} -gt 0 ]]; then
  ./scripts/models-install.sh "$@"
else
  ./scripts/models-install.sh
fi

touch "$SENTINEL"
echo "[install] Done. Sentinel: $SENTINEL"
